# Generated by Django 3.2.5 on 2021-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='about',
            table='About',
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='items',
            table='Items',
        ),
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
        migrations.AlterModelTable(
            name='subscribe',
            table='Subscribe',
        ),
        migrations.AlterModelTable(
            name='video',
            table='Video',
        ),
    ]
